#   Copyright (c) European Space Agency, 2025.
#
#   This file is subject to the terms and conditions defined in file 'LICENCE.txt', which
#   is part of this source code package. No part of the package, including
#   this file, may be copied, modified, propagated, or distributed except according to
#   the terms contained in the file 'LICENCE.txt'.
name: am
channels:
  - conda-forge
  - pytorch
dependencies:
  - astropy
  - dotmap
  - h5py
  - imageio
  - ipykernel
  - ipywidgets
  - loguru
  - matplotlib
  - numpy
  - pandas<3
  - python=3.11
  - pytorch>=2.6
  - pytest
  - pytest-cov
  - pytest-asyncio>=0.23.0
  - pyturbojpeg
  - scikit-learn
  - scikit-image
  - toml
  - torchvision
  - tqdm
  - zarr>=3.0.0b0
  - pip
  - pip:
      - opencv-python-headless
      - albumentations
      - safetensors
      - timm
      - fitsbolt==0.2.0
      - cutana>=0.3.0
