#   Copyright (c) European Space Agency, 2025.
#
#   This file is subject to the terms and conditions defined in file 'LICENCE.txt', which
#   is part of this source code package. No part of the package, including
#   this file, may be copied, modified, propagated, or distributed except according to
#   the terms contained in the file ‘LICENCE.txt’.
name: am
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - dotmap
  - efficientnet-pytorch
  - h5py
  - imageio
  - ipykernel
  - ipywidgets
  - loguru
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - pytorch
  - pytorch-cuda=12.4
  - pyturbojpeg
  - scikit-learn
  - scikit-image
  - toml
  - torchvision
  - tqdm
  - pip
  - pip:
      - albumentations
      - efficientnet_lite_pytorch
      - efficientnet_lite0_pytorch_model
      - opencv-python-headless
